name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pages: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Remove PR directory
        run: |
          if [ -d "pr-${{ github.event.number }}" ]; then
            rm -rf "pr-${{ github.event.number }}"
            git config user.name 'github-actions[bot]'
            git config user.email 'github-actions[bot]@users.noreply.github.com'
            git add .
            git commit -m "cleanup: Remove preview for PR #${{ github.event.number }}" || exit 0
            git push
          fi

      - name: Comment on PR about cleanup
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## 🧹 Preview Cleanup
            
            The preview deployment for this PR has been removed.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });
