name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages # Check out to a specific path to avoid conflicts

      - name: Remove PR preview directory
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          directory_to_remove="pr-${{ github.event.number }}"

          if [ -d "$directory_to_remove" ]; then
            git rm -rf "$directory_to_remove"
            git commit -m "Remove preview for PR #${{ github.event.number }}"
            git push
            echo "Successfully removed directory $directory_to_remove and pushed changes."
          else
            echo "Directory $directory_to_remove does not exist. No cleanup needed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # git push needs token

      - name: Comment on PR about cleanup
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## 🧹 Preview Cleanup
            
            The preview deployment for this PR (directory pr-${{ github.event.number }}) should now be removed.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });
