name: PR Preview Cleanup

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on PR about cleanup
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `## 🧹 Preview Cleanup
            
            The preview deployment for this PR has been removed.`;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.pull_request.number,
              body: comment
            });
